// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyActYrIs_oR19Hs4F-IeG7zUqOcVJ4p7_A',
    appId: '1:963987269530:web:3f037a7e4249ef04c5bc23',
    messagingSenderId: '963987269530',
    projectId: 'task-trader-aed54',
    authDomain: 'task-trader-aed54.firebaseapp.com',
    storageBucket: 'task-trader-aed54.firebasestorage.app',
    measurementId: 'G-HG8F7VMEJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCul7enRi314d4VtNPRD6Khnhjl5lBiK7s',
    appId: '1:963987269530:android:defd217f8507ecbcc5bc23',
    messagingSenderId: '963987269530',
    projectId: 'task-trader-aed54',
    storageBucket: 'task-trader-aed54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcOWuJNW7N25SCu6c1WELJnGW5n8bowXQ',
    appId: '1:963987269530:ios:d3ae7168cac93553c5bc23',
    messagingSenderId: '963987269530',
    projectId: 'task-trader-aed54',
    storageBucket: 'task-trader-aed54.firebasestorage.app',
    iosBundleId: 'com.example.taskTrader',
  );
}
